apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grapp.fullname" . }}
  labels: 
{{ include "grapp.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }} 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "grapp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "grapp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      containers:
        - name: {{ .Values.app }} 
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.image.containerPort }} 
          envFrom:
            - secretRef:
                name: {{ .Values.app }}-secret
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.image.containerPort }}
            initialDelaySeconds: 300
            periodSeconds: 30
            successThreshold: 2
            failureThreshold: 4
